servers:
  # @ConfigurationProperties绑定属性支持属性名宽松绑定
  ipAddress: 192.168.0.1   # 驼峰模式
#  ipaddress: 192.168.0.1
#  ip_address: 192.168.0.1  # 下划线模式
#  ip-address: 192.168.0.2  # 中划线模式 推荐模式
#  IPADDRESS: 192.168.0.1
#  IP_ADDRESS: 192.168.0.1  # 常量模式
  port: 2345
  timeout: -1
  server-time-out: 3
#  data-size: 10MB
  data-size: 10
datasource:
  driver-class-name: com.mysql.jdbc.Driver

# yaml 语法规则
# boolean: TRUE  			#TRUE,true,True,FALSE,false，False均可
# float: 3.14    			#6.8523015e+5  支持科学计数法
# int: 123       			#0b1010_0111_0100_1010_1110  支持二进[0b(0-1)]、八进制[0(0-7)]、十六进制[0x(0-9,a-f)]
# null: ~        			#使用~表示null
# string: HelloWorld        #字符串可以直接书写
# string2: "Hello World"  	#可以使用双引号包裹特殊字符
# date: 2018-02-17        	#日期必须使用yyyy-MM-dd格式
# datetime: 2018-02-17T15:02:31+08:00  #时间和日期之间使用T连接，最后使用+代表时区
