#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test
#      username: eric
#      password: 1234

# SpringBoot内置3款数据源可供选择
# - HikariCP（默认）
# - Tomcat提供DataSource
# - Commons DBCP

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    hikari:
      username: eric
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
#    tomcat:
#    dbcp2:
  jdbc:
    template:
      max-rows: 1000
      fetch-size: 100
      query-timeout: -1

#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tbl_
#      id-type: AUTO
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.eric.mapper: debug

