server:
  port: 81

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://120.26.107.127:3306/test
      username: eric
      password: 1234
  boot:
    admin:
      client:
        url:
          - http://localhost:8080

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: AUTO
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.eric.mapper: debug

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - "*"
