server:
  port: 80

#debug: true

logging:
  # 设置分组
  group:
    eric: com.eric.controller,com.eric.service,com.eric.dao
    iservice: com.alibaba
  level:
    root: info
    # 设置单个包的日志级别
#    com.eric.controller: debug

    # 设置分组，对某个组设置日志级别
    eric: warn

