server:
  port: 80

spring:

# <-- activemq -->
#  activemq:
#    broker-url: tcp://localhost:61616
#  jms:
#    # 将模型从点对点改为发布订阅
#    pub-sub-domain: true
#    template:
#      default-destination: eric

# <-- rabbitmq -->
#  rabbitmq:
#    host: localhost
#    port: 5672

# <-- rocketmq -->
rocketmq:
  name-server: localhost:9876
  producer:
    group: group_rocketmq
