spring:
  redis:
    host: localhost
    port: 6379
    client-type: JEDIS
    jedis:
      pool:
        max-active: 10
    lettuce:
      pool:
        max-active: 10

# ↓ lettcus与jedis区别
# jedis连接Redis服务器是直连模式，当多线程模式下使用jedis会存在线程安全问题，解决方案可以通过配置连接池使每个连接专用，这样整体性能就大受影响。
# lettcus基于Netty框架进行与Redis服务器连接，底层设计中采用StatefulRedisConnection。 StatefulRedisConnection自身是线程安全的，可以保障并发访问安全问题，所以一个连接可以被多线程复用。当然lettcus也支持多连接实例一起工作。
